### ISSUE TITLE
Please explain how to use in blazor wasm hosted template

### ISSUE THREAD

**Issue by mammadkoma** [danroth27/Net8BlazorAuto#1]
I created a blazor wasm hosted (3 projects : client, server, shared) last year with .net 7 and upgrade it this year to .net 8 and it works. Please explain how to use RenderModeAuto in blazor wasm hosted template. I want to load all project pages in RenderModeAuto for increasing startup time. 
Is it possible? 
If not what kind of template should we create in vs 2022 preview Version 17.8.0 for making the pages in RenderModeAuto for increasing startup time and download the wasm dll files in the background?

**Comment by danroth27** [comment]
Hi @mammadkoma. For upgrading an existing Blazor WebAssembly app to use the new Auto render mode in .NET 8 you will need to make a few changes to switch to the Blazor Web App model with interactivity enabled at the root of the app. I'm working on a sample and guidance for this process here: https://github.com/danroth27/Net8BlazorWebAssembly.
