### ISSUE TITLE
Auto mode by default

### ISSUE THREAD

**Issue by dajma00** [danroth27/Net8BlazorAuto#5]
Is it possible to assign Auto mode to all the app components, without specifying for each component using the `@attribute [RenderModeAuto]`?

**Comment by danroth27** [comment]
@dajma00 Yup, you can setup the Auto render mode in the app root if you want, but you'll need to move any code you want to run on the client to the client project. We're adding a template option to the Blazor Web App template that will set this up for you: https://github.com/dotnet/aspnetcore/pull/50684
